inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

AllCops:
  TargetRubyVersion: 3.1

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/PerceivedComplexity:
  Max: 12

Layout/LineLength:
  Max: 120
